services:
  resource-server:
    container_name: resource-server
    image: resource-server
    restart: on-failure
    ports:
      - 2222:22
      - 8080:8080
    networks:
      - service-network

  jenkins:
    container_name: jenkins
    image: jenkins
    restart: on-failure
    ports:
      - 8081:8080
    networks:
      - service-network

networks:
  service-network:
    name: service-network