FROM ubuntu:22.04

RUN apt update && apt install -y openssh-server
RUN echo 'root:root' | chpasswd
RUN mkdir /server
RUN mkdir -p ~/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCCSj0WpkBowmNAWZPYTsT5BkxtWLm6cEe/6LWn9Av/vAsdxjN4rXB7BiMKit4PAMAzTyb4zvNNRYoS/hFCa9LKhBEZ16W/W5rGpMV3nvoxqynCFyWkd3tqO8mGPlDJdTFI2sQjHegSQW1aPDoWhGltiKcGZKTAgDJtkYfYEOSQISZ/JlFuIN0C+U0jmnUNfGchkGzArda3djaScf94qqONwrkHCirX7r4k30R/pD0S15uX54LW/7uyqUy+cmhLCmJuYw3GmIvI1winFyxT2+7C2ZQvbDV04su3hOUZjKoyFE/a8Q9djNLLPWhQQj4FE6gpictSMu+hcyjA61co1jWt coerschkes@linux-dev" >> ~/.ssh/authorized_keys
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

CMD ["/usr/sbin/sshd", "-D"]