# https://www.digitalocean.com/community/tutorials/how-to-automate-jenkins-setup-with-docker-and-jenkins-configuration-as-code

FROM ubuntu:22.04

RUN apt update && apt install -y openssh-server openjdk-21-jre
RUN echo 'root:root' | chpasswd
RUN mkdir /server
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
COPY restart.sh /server/restart.sh
RUN chmod +x /server/restart.sh

CMD ["/usr/sbin/sshd", "-D"]